-- ADICIONAR CAMPOS FALTANTES EM bulk_sales PARA O DASHBOARD
ALTER TABLE bulk_sales 
  ADD COLUMN IF NOT EXISTS is_paid     BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS is_received BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS signature_base64 TEXT;
